#version 420

// original https://www.shadertoy.com/view/wstcDH

uniform float time;
uniform vec2 mouse;
uniform vec2 resolution;

out vec4 glFragColor;

#define TAU (2.0*3.1415926)

/**
You help her onto her horse and the both of you gallop back
to the ritual. The sun is setting, casting the entire forest
into darkness. The moon is out, and the forest glows with an
otherworldly light. Your horse runs fast, but Zal's seems to
move even faster. She reaches the stone circle first and
dismounts, running towards the center. As she runs, she pushes
the altar with her, overturning it so that the pentagram is
now upside-down.

-- Text generated by AI Dungeon
https://play.aidungeon.io
*/

// Hash functions by Dave Hoskins
// https://www.shadertoy.com/view/4djSRW
vec3 hash32(vec2 p)
{
    vec3 p3 = fract(vec3(p.xyx) * vec3(.1031, .1030, .0973));
    p3 += dot(p3, p3.yxz+33.33);
    return fract((p3.xxy+p3.yzz)*p3.zyx);
}

vec2 coo;

float sdBox( vec3 p, vec3 r )
{
    vec3 q = abs(p) - r;
    return length(max(q,0.)) + min(max(q.x,max(q.y,q.z)),0.);
}

vec3 tri(vec3 p)
{
    return abs(fract(p)-0.5)-0.25;
}

float map( vec3 p, out vec3 q )
{
    // Terrain deformation
    p.z += cos(p.y*0.1) - cos(p.x*0.162);
    
    // For each point, calculate the distance to one stone only
    float nStones = 13.;
    float circleRadius = 5.0;
    float d = 100.;
    float th = atan(p.y, p.x);
    float id = round(th/TAU * nStones);
    vec2 cs = cos(TAU*id/nStones + vec2(0.,-TAU*0.25));
    q = p;
    // Bring back point close to the positive x axis
    q.xy *= mat2(cs.x,cs.y,-cs.y,cs.x);
    
    // Make sure the rays don't go too far into the next stone's section
    float dSection = length(abs(q.xy) - circleRadius*cos(TAU/nStones+vec2(0.,-TAU/4.))) - 1.0;
    dSection = max(dSection, p.z - 2.0);
    d = min(d, dSection);
    
    // Random size of stone block
    vec3 blockSize = 0.1+vec3(0.5,0.5,1.5)*hash32(cs);
    q.x -= circleRadius;
    q.z -= 0.5*blockSize.z;
    // Tilt stone by 45 degrees at most
    cs = abs(cs); cs.xy = cs.x < cs.y ? cs.xy : cs.yx;
    q.xz *= mat2(cs.y,cs.x,-cs.x,cs.y);
    float dBox = sdBox(q, blockSize);
    // Deform surface a bit
    vec3 q2 = p;
    q2.yz *= mat2(0.6,0.8,-0.8,0.6);
    dBox += 0.3*dot(tri(q2), vec3(0.666));
    d = min(d, dBox);
    
    d = min(d, p.z);
    
    // I would like to add some stones popping off the ground,
    // but doing it this way seems to introduce discontinuities.
    // Use a Voronoi pattern ?
    #if 1
    q2 += hash32(floor(p.xy+0.5));
    d = min(d, p.z + 0.15 - 0.1*sin(p.y*0.2)*cos(p.x*0.4) + 0.5*dot(tri(q2), vec3(0.666)));
    #endif
    q = p;
    return d;
}

float map(vec3 p)
{
    vec3 q; return map(p,q);
}

vec3 normal( vec3 p )
{
    vec2 e = 0.001 * vec2(1, -1);
    return normalize(
          e.xxx * map(p+e.xxx)
        + e.xyy * map(p+e.xyy)
        + e.yxy * map(p+e.yxy)
        + e.yyx * map(p+e.yyx)
    );
}

// Ambient Occlusion computation stolen from iq
// https://www.shadertoy.com/view/Xds3zN
float calcAO( in vec3 pos, in vec3 nor )
{
    float occ = 0.0;
    float sca = 1.0;
    for( int i=0; i<5; i++ )
    {
        float h = 0.01 + 0.12*float(i)/4.0;
        float d = map( pos + h*nor );
        occ += (h-d)*sca;
        sca *= 0.95;
        if( occ>0.5 ) break;
    }
    return clamp( 1.0 - 2.0*occ, 0.0, 1.0 ) * (0.5+0.5*nor.z);
}

float calcSoftShadows( vec3 ro, vec3 rd, float softness )
{
    float transm = 1.0;
    float d, t=0.01 + hash32(coo).x*map(ro);
    for(int i=0; i<256; i++)
    {
        float w = softness * t;
        d = map(ro+t*rd);
        transm = min(transm, smoothstep(-w,w,d));
        if(transm < 0.01 || t > 20.) break;
        t += d+w;
        //t += max(d, 0.02);
    }
    return transm;
}

void main(void)
{
    coo = gl_FragCoord.xy;
    vec2 uv = (2.0*gl_FragCoord.xy - resolution.xy)/resolution.y;

    float th = 3.1415*0.5*(0.5+0.5*asin(0.9*sin(0.1*time)));
    vec3 ro = vec3(-10.*cos(th),10.*sin(th),1.5);
    vec3 camFwd = normalize(vec3(0) - ro);
    vec3 camRight = normalize(cross(camFwd, vec3(0,0,1)));
    vec3 camUp = cross(camRight, camFwd);
    float fov = 0.5;
    vec3 rd = normalize(camFwd + fov * (uv.x * camRight + uv.y * camUp));
    
    float d, t=0.;
    for(int i=0; i<256; i++)
    {
        d = map(ro+t*rd);
        if(d < 0.001 || t > 100.) break;
        t += d*0.7;
    }
    vec3 p = ro+t*rd;
    vec3 n = normal(p);
    vec3 col;
    
    vec3 skyCol = vec3(1.0,1.5,2.);
    vec3 sunDir = normalize(vec3(1,-1,0.1));
    //vec3 sunCol = vec3(2.,1.5,1.0);
    vec3 sunCol = vec3(1.0, 0.25, 0.1); // Sunset
    if(t > 100.)
    {
        col = skyCol * 0.4;
        vec3 rd_mod = normalize(vec3(rd.xy+sunDir.xy, rd.z*5.0));
        col += sunCol * pow(clamp(dot(rd_mod, sunDir),0.,1.), 10.)*0.6;
        col += 5.0*sunCol * pow(clamp(dot(rd, sunDir),0.,1.), 10000.);
    }
    else
    {
        //col = 0.5+0.5*n;
        col = vec3(0);
        vec3 q; map(p,q);
        vec3 grassCol = vec3(0.3,0.5,0.2);
        vec3 stoneCol = vec3(0.2,0.21,0.22)*1.5;
        vec3 surfCol = mix(grassCol, stoneCol, 
                           smoothstep(0.,0.01,q.z));
        float ao = calcAO(p, n);
        float shadow = calcSoftShadows(p+0.01*n, sunDir, 0.1);
        
        col += sunCol * shadow * surfCol * 8.;
        col += ao * 0.1 * skyCol * (0.5 + 0.5*n.z);
        vec3 fillDir = vec3(-sunDir.xy, 0.);
        //vec3 fillCol = 0.05*sunCol*grassCol;
        //col += fillCol * clamp(dot(n, fillDir), 0., 1.);
        
        float fog = 1.-exp(-0.02*max(t-10.,0.));
        col = mix(col, skyCol*0.4, fog);
    }
    
    col += sunCol * pow(clamp(dot(rd, sunDir),0.,1.), 8.)*1.5;
    
    col = mix(col, 1.-4./27./(col*col), step(2./3.,col));
    col = pow(col, vec3(1./2.2));
    glFragColor = vec4(col, 1.);
}
