# -*- coding: utf-8 -*-
"""min-dalle

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/kuprel/min-dalle/blob/main/min_dalle.ipynb

# min(DALL·E)

### Install
"""

#! pip install min-dalle

"""### Load Model"""

from min_dalle import MinDalle

model = MinDalle(is_mega=True, is_reusable=True)

"""### Generate Images
Note: a 3x3 grid will not work in the standard runtime
"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
text = "court sketch of godzilla on trial" #@param {type:"string"}
seed = 6 #@param {type:"integer"}
grid_size = 2 #@param {type:"integer"}
# 
# display(model.generate_image(text, seed, grid_size))
model.generate_image(text, seed, grid_size).save('results.png')