# -*- coding: utf-8 -*-

"""modelscope_text2vid

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bhfWR16IB9BrEEFFKg_GaWoUkD6T-u3i

Testing an open-weights text2video model from modelscope - see the [tweet by AK](https://twitter.com/_akhaliq/status/1637321077553606657).

If you want a more user-friendly interface check out the [demo on Hugging Face](https://huggingface.co/spaces/damo-vilab/modelscope-text-to-video-synthesis).

- Model page: [modelscope.cn/models/damo/text-to-video-synthesis/](https://modelscope.cn/models/damo/text-to-video-synthesis/)
- Model weights: [modelscope.cn/models/damo/text-to-video-synthesis/files](https://modelscope.cn/models/damo/text-to-video-synthesis/files)
  - weights will be downloaded automatically once you load the pipeline, ~15GB total.
- Main library: [github.com/modelscope/modelscope](https://github.com/modelscope/modelscope)

Notebook by [@mdnest_r](https://twitter.com/mdnest_r). Thanks to [@JiuniuWang](https://twitter.com/JiuniuWang) for bugfixes.
"""

import sys

sys.stdout.write("Imports ...\n")
sys.stdout.flush()

import os

import torch
import argparse

sys.stdout.write("Parsing arguments ...\n")
sys.stdout.flush()

def parse_args():
  desc = "Blah"
  parser = argparse.ArgumentParser(description=desc)
  parser.add_argument('--prompt', type=str, help='Prompt.')
  args = parser.parse_args()
  return args

args=parse_args();

device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
print('Using device:', device, flush=True)
print(torch.cuda.get_device_properties(device), flush=True)
sys.stdout.flush()

sys.stdout.write("Initializing pipeline and downloading weights if required ...\n")
sys.stdout.flush()

from modelscope.pipelines import pipeline
from modelscope.outputs import OutputKeys

p = pipeline("text-to-video-synthesis", "damo/text-to-video-synthesis")

test_text = {
        'text': args.prompt,
    }

sys.stdout.write("Generating frames ...\n")
sys.stdout.flush()

output_video_path = p(test_text,)[OutputKeys.OUTPUT_VIDEO]
print('output_video_path:', output_video_path)